name: F# CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v3

    - name: .NET SDK のセットアップ
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: F# のコードをビルド
      run: dotnet build

    - name: F# のコードをテスト
      run: dotnet test
